=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec.schema.json
{
  "$id": "https://handlebars.knappi.org/schemas/spec.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "This file describes the format of a handlebars-test specification",
  "type": "object",
  "properties": {
    "description": {
      "type": "string",
      "description": "A description of what should be tested in this file"
    },
    "template": {
      "type": "string",
      "description": "The original template that should be compiled"
    },
    "ast": {
      "additionalProperties": true,
      "description": "The AST that is expected to be returned by the parser"
    },
    "input": {
      "additionalProperties": true,
      "description": "The input object"
    },
    "helpers": {
      "additionalProperties": {
        "description": "The filename of the helper inside the 'language-specific' directory",
        "type": "string"
      }
    },
    "output": {
      "type": "string"
    },
    "failsInOriginalHandlebars": {
      "description": "Indicates that this test fails in the original Handlebars (4.x), but in my opinion this should be correct",
      "type": "boolean"
    }
  },
  "required": ["description","ast","input","output","template"]
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/02-abstract-syntax-tree/newline-around-mustache.hb-spec.json
{
  "$schema": "../spec.schema.json",
  "description": "Newlines around a mustache statement",
  "template": "\n{{a}}\n",
  "input": { "a": 2 },
  "output": "\n2\n",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "value": "\n",
        "original": "\n",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 2, "column": 0 }
        }
      },
      {
        "type": "MustacheStatement",
        "escaped": true,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "a",
          "data": false,
          "depth": 0,
          "parts": ["a"],
          "loc": {
            "start": { "line": 2, "column": 2 },
            "end": { "line": 2, "column": 3 }
          }
        },
        "strip": { "open": false, "close": false },
        "loc": {
          "start": { "line": 2, "column": 0 },
          "end": { "line": 2, "column": 5 }
        }
      },
      {
        "type": "ContentStatement",
        "value": "\n",
        "original": "\n",
        "loc": {
          "start": { "line": 2, "column": 5 },
          "end": { "line": 3, "column": 0 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 3, "column": 0 }
    }
  }
}

=== nknapp/handlebars-ng/packages/website/src/pages/spec/01-introduction/example.hb-spec.json
{
  "$schema": "../spec.schema.json",
  "description": "A basic example with one mustache",
  "template": "Hello {{something}}",
  "input": { "something": "world" },
  "output": "Hello world",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "original": "Hello ",
        "value": "Hello ",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 6 }
        }
      },
      {
        "type": "MustacheStatement",
        "path": {
          "type": "PathExpression",
          "data": false,
          "depth": 0,
          "parts": ["something"],
          "original": "something",
          "loc": {
            "start": { "line": 1, "column": 8 },
            "end": { "line": 1, "column": 17 }
          }
        },
        "params": [],
        "escaped": true,
        "strip": { "open": false, "close": false },
        "loc": {
          "start": { "line": 1, "column": 6 },
          "end": { "line": 1, "column": 19 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 19 }
    }
  }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/02-abstract-syntax-tree/newline.hb-spec.json
{
  "$schema": "../spec.schema.json",
  "description": "A single newline",
  "template": "\n",
  "output": "\n",
  "input": {},
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "value": "\n",
        "original": "\n",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 2, "column": 0 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 2, "column": 0 }
    }
  }
}

=== nknapp/handlebars-ng/packages/website/src/pages/spec/02-abstract-syntax-tree/newline.hb-spec.json
{
  "$schema": "../spec.schema.json",
  "description": "A single newline",
  "template": "\n",
  "output": "\n",
  "input": {},
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "original": "\n",
        "value": "\n",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 2, "column": 0 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 2, "column": 0 }
    }
  }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/pages/spec/02-abstract-syntax-tree/newline-around-mustache.hb-spec.json
{
  "$schema": "../spec.schema.json",
  "description": "Newlines around a mustache statement",
  "template": "\n{{a}}\n",
  "input": { "a": 2 },
  "output": "\n2\n",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "original": "\n",
        "value": "\n",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 2, "column": 0 }
        }
      },
      {
        "type": "MustacheStatement",
        "path": {
          "type": "PathExpression",
          "data": false,
          "depth": 0,
          "parts": ["a"],
          "original": "a",
          "loc": {
            "start": { "line": 2, "column": 2 },
            "end": { "line": 2, "column": 3 }
          }
        },
        "params": [],
        "escaped": true,
        "strip": { "open": false, "close": false },
        "loc": {
          "start": { "line": 2, "column": 0 },
          "end": { "line": 2, "column": 5 }
        }
      },
      {
        "type": "ContentStatement",
        "original": "\n",
        "value": "\n",
        "loc": {
          "start": { "line": 2, "column": 5 },
          "end": { "line": 3, "column": 0 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 3, "column": 0 }
    }
  }
}
