=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/schema/testcase.json
{
  "$ref": "#/definitions/HandlebarsTest",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ContentStatement": {
      "additionalProperties": false,
      "properties": {
        "loc": {
          "$ref": "#/definitions/SourceLocation"
        },
        "original": {
          "type": "string"
        },
        "type": {
          "const": "ContentStatement",
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "loc",
        "original",
        "type",
        "value"
      ],
      "type": "object"
    },
    "HandlebarsTest": {
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "ast": {
          "$ref": "#/definitions/Program"
        },
        "description": {
          "type": "string"
        },
        "helpers": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "input": {
          "additionalProperties": {},
          "type": "object"
        },
        "originalAst": {
          "description": "The AST created by the original Handlebars parser, in case it is different from \"ast\""
        },
        "originalParseError": {
          "const": true,
          "description": "The original Handlebars parser cannot parse the template in this test",
          "type": "boolean"
        },
        "output": {
          "type": "string"
        },
        "possibleBug": {
          "description": "If the output of Handlebars.js seems to be wrong, a description of this should be in this field.  That way, we can discuss the issues later. For now we should try to remain backwards compatible, so the \"output\" field should be what Handlebars 4.x is creating.",
          "type": "string"
        },
        "template": {
          "type": "string"
        }
      },
      "required": [
        "$schema",
        "description",
        "template",
        "ast",
        "input",
        "output"
      ],
      "type": "object"
    },
    "MustacheStatement": {
      "additionalProperties": false,
      "properties": {
        "escaped": {
          "type": "boolean"
        },
        "loc": {
          "$ref": "#/definitions/SourceLocation"
        },
        "params": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "path": {
          "$ref": "#/definitions/PathExpression"
        },
        "strip": {
          "$ref": "#/definitions/StripFlags"
        },
        "type": {
          "const": "MustacheStatement",
          "type": "string"
        }
      },
      "required": [
        "escaped",
        "loc",
        "params",
        "path",
        "strip",
        "type"
      ],
      "type": "object"
    },
    "PathExpression": {
      "additionalProperties": false,
      "properties": {
        "data": {
          "type": "boolean"
        },
        "depth": {
          "type": "number"
        },
        "loc": {
          "$ref": "#/definitions/SourceLocation"
        },
        "original": {
          "type": "string"
        },
        "parts": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "type": {
          "const": "PathExpression",
          "type": "string"
        }
      },
      "required": [
        "data",
        "depth",
        "loc",
        "original",
        "parts",
        "type"
      ],
      "type": "object"
    },
    "Position": {
      "additionalProperties": false,
      "properties": {
        "column": {
          "type": "number"
        },
        "line": {
          "type": "number"
        }
      },
      "required": [
        "line",
        "column"
      ],
      "type": "object"
    },
    "Program": {
      "additionalProperties": false,
      "properties": {
        "blockParams": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "body": {
          "items": {
            "$ref": "#/definitions/Statement"
          },
          "type": "array"
        },
        "loc": {
          "$ref": "#/definitions/SourceLocation"
        },
        "strip": {
          "additionalProperties": {
            "not": {}
          },
          "type": "object"
        },
        "type": {
          "const": "Program",
          "type": "string"
        }
      },
      "required": [
        "body",
        "loc",
        "strip",
        "type"
      ],
      "type": "object"
    },
    "SourceLocation": {
      "additionalProperties": false,
      "properties": {
        "end": {
          "$ref": "#/definitions/Position"
        },
        "source": {
          "type": "string"
        },
        "start": {
          "$ref": "#/definitions/Position"
        }
      },
      "required": [
        "start",
        "end"
      ],
      "type": "object"
    },
    "Statement": {
      "anyOf": [
        {
          "$ref": "#/definitions/ContentStatement"
        },
        {
          "$ref": "#/definitions/MustacheStatement"
        }
      ]
    },
    "StripFlags": {
      "additionalProperties": false,
      "properties": {
        "close": {
          "type": "boolean"
        },
        "open": {
          "type": "boolean"
        }
      },
      "required": [
        "open",
        "close"
      ],
      "type": "object"
    }
  }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/05-mustache-statement/white-space-control-unescaped.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "White space should be removed when control characters are in place",
  "template": "|- {{{~name}}} | {{{name~}}} -|- {{{~name~}}} -|",
  "input": { "name": "joe" },
  "output": "|-joe | joe-|-joe-|",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "original": "|- ",
        "value": "|- ",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 3 }
        }
      },
      {
        "type": "MustacheStatement",
        "path": {
          "type": "PathExpression",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "original": "name",
          "loc": {
            "start": { "line": 1, "column": 7 },
            "end": { "line": 1, "column": 11 }
          }
        },
        "params": [],
        "escaped": false,
        "strip": { "open": true, "close": false },
        "loc": {
          "start": { "line": 1, "column": 3 },
          "end": { "line": 1, "column": 14 }
        }
      },
      {
        "type": "ContentStatement",
        "original": " | ",
        "value": " | ",
        "loc": {
          "start": { "line": 1, "column": 14 },
          "end": { "line": 1, "column": 17 }
        }
      },
      {
        "type": "MustacheStatement",
        "path": {
          "type": "PathExpression",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "original": "name",
          "loc": {
            "start": { "line": 1, "column": 20 },
            "end": { "line": 1, "column": 24 }
          }
        },
        "params": [],
        "escaped": false,
        "strip": { "open": false, "close": true },
        "loc": {
          "start": { "line": 1, "column": 17 },
          "end": { "line": 1, "column": 28 }
        }
      },
      {
        "type": "ContentStatement",
        "original": " -|- ",
        "value": " -|- ",
        "loc": {
          "start": { "line": 1, "column": 29 },
          "end": { "line": 1, "column": 45 }
        }
      },
      {
        "type": "MustacheStatement",
        "path": {
          "type": "PathExpression",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "original": "name",
          "loc": {
            "start": { "line": 1, "column": 37 },
            "end": { "line": 1, "column": 41 }
          }
        },
        "params": [],
        "escaped": false,
        "strip": { "open": true, "close": true },
        "loc": {
          "start": { "line": 1, "column": 33 },
          "end": { "line": 1, "column": 45 }
        }
      },
      {
        "type": "ContentStatement",
        "original": " -|",
        "value": " -|",
        "loc": {
          "start": { "line": 1, "column": 39 },
          "end": { "line": 1, "column": 42 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 42 }
    }
  },
  "originalParseError": true
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/02-abstract-syntax-tree/empty.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "An empty template yields an empty result",
  "template": "",
  "ast": {
    "type": "Program",
    "body": [],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 1 }
    }
  },
  "input": {},
  "output": "",
  "originalAst": { "type": "Program", "body": [], "strip": {} }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/pages/spec/03-template-syntax/escaped-content.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "Escape mustache expression",
  "template": "abc \\{{ cde",
  "input": {},
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "original": "abc {{ cde",
        "value": "abc {{ cde",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 11 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 11 }
    }
  },
  "originalAst": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "original": "abc ",
        "value": "abc ",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 5 }
        }
      },
      {
        "type": "ContentStatement",
        "original": "{{ cde",
        "value": "{{ cde",
        "loc": {
          "start": { "line": 1, "column": 5 },
          "end": { "line": 1, "column": 11 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 11 }
    }
  },
  "output": "abc {{ cde"
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/05-mustache-statement/white-space-control-empty-nodes.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "ContentStatements that become empty due to white-space control, are preserved.",
  "template": " {{~name~}} {{~name~}}",
  "input": { "name": "joe" },
  "output": "joejoe",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "value": "",
        "original": " ",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 1 }
        }
      },
      {
        "type": "MustacheStatement",
        "escaped": true,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "name",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "loc": {
            "start": { "line": 1, "column": 4 },
            "end": { "line": 1, "column": 8 }
          }
        },
        "strip": { "open": true, "close": true },
        "loc": {
          "start": { "line": 1, "column": 1 },
          "end": { "line": 1, "column": 11 }
        }
      },
      {
        "type": "ContentStatement",
        "value": "",
        "original": " ",
        "loc": {
          "start": { "line": 1, "column": 11 },
          "end": { "line": 1, "column": 12 }
        }
      },
      {
        "type": "MustacheStatement",
        "escaped": true,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "name",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "loc": {
            "start": { "line": 1, "column": 15 },
            "end": { "line": 1, "column": 19 }
          }
        },
        "strip": { "open": true, "close": true },
        "loc": {
          "start": { "line": 1, "column": 12 },
          "end": { "line": 1, "column": 22 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 22 }
    }
  }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/05-mustache-statement/html-escaped-mustache.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "A simple mustache with html-escaped output",
  "template": "{{ value }}",
  "input": { "value": "abc & < > \" ' ` = 123" },
  "output": "abc &amp; &lt; &gt; &quot; &#x27; &#x60; &#x3D; 123",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "MustacheStatement",
        "path": {
          "type": "PathExpression",
          "data": false,
          "depth": 0,
          "parts": ["value"],
          "original": "value",
          "loc": {
            "start": { "line": 1, "column": 3 },
            "end": { "line": 1, "column": 8 }
          }
        },
        "params": [],
        "escaped": true,
        "strip": { "open": false, "close": false },
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 11 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 11 }
    }
  }
}
