=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/schema/testcase.json
{
  "$ref": "#/definitions/HandlebarsTest",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ContentStatement": {
      "additionalProperties": false,
      "properties": {
        "loc": {
          "$ref": "#/definitions/SourceLocation"
        },
        "original": {
          "type": "string"
        },
        "type": {
          "const": "ContentStatement",
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "loc",
        "original",
        "type",
        "value"
      ],
      "type": "object"
    },
    "HandlebarsTest": {
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "ast": {
          "$ref": "#/definitions/Program"
        },
        "description": {
          "type": "string"
        },
        "helpers": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "input": {
          "additionalProperties": {},
          "type": "object"
        },
        "originalAst": {
          "description": "The AST created by the original Handlebars parser, in case it is different from \"ast\""
        },
        "originalParseError": {
          "const": true,
          "description": "The original Handlebars parser cannot parse the template in this test",
          "type": "boolean"
        },
        "output": {
          "type": "string"
        },
        "possibleBug": {
          "description": "If the output of Handlebars.js seems to be wrong, a description of this should be in this field.  That way, we can discuss the issues later. For now we should try to remain backwards compatible, so the \"output\" field should be what Handlebars 4.x is creating.",
          "type": "string"
        },
        "template": {
          "type": "string"
        }
      },
      "required": [
        "$schema",
        "description",
        "template",
        "ast",
        "input",
        "output"
      ],
      "type": "object"
    },
    "MustacheStatement": {
      "additionalProperties": false,
      "properties": {
        "escaped": {
          "type": "boolean"
        },
        "loc": {
          "$ref": "#/definitions/SourceLocation"
        },
        "params": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "path": {
          "$ref": "#/definitions/PathExpression"
        },
        "strip": {
          "$ref": "#/definitions/StripFlags"
        },
        "type": {
          "const": "MustacheStatement",
          "type": "string"
        }
      },
      "required": [
        "escaped",
        "loc",
        "params",
        "path",
        "strip",
        "type"
      ],
      "type": "object"
    },
    "PathExpression": {
      "additionalProperties": false,
      "properties": {
        "data": {
          "type": "boolean"
        },
        "depth": {
          "type": "number"
        },
        "loc": {
          "$ref": "#/definitions/SourceLocation"
        },
        "original": {
          "type": "string"
        },
        "parts": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "type": {
          "const": "PathExpression",
          "type": "string"
        }
      },
      "required": [
        "data",
        "depth",
        "loc",
        "original",
        "parts",
        "type"
      ],
      "type": "object"
    },
    "Position": {
      "additionalProperties": false,
      "properties": {
        "column": {
          "type": "number"
        },
        "line": {
          "type": "number"
        }
      },
      "required": [
        "line",
        "column"
      ],
      "type": "object"
    },
    "Program": {
      "additionalProperties": false,
      "properties": {
        "blockParams": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "body": {
          "items": {
            "$ref": "#/definitions/Statement"
          },
          "type": "array"
        },
        "loc": {
          "$ref": "#/definitions/SourceLocation"
        },
        "strip": {
          "additionalProperties": {
            "not": {}
          },
          "type": "object"
        },
        "type": {
          "const": "Program",
          "type": "string"
        }
      },
      "required": [
        "body",
        "loc",
        "strip",
        "type"
      ],
      "type": "object"
    },
    "SourceLocation": {
      "additionalProperties": false,
      "properties": {
        "end": {
          "$ref": "#/definitions/Position"
        },
        "source": {
          "type": "string"
        },
        "start": {
          "$ref": "#/definitions/Position"
        }
      },
      "required": [
        "start",
        "end"
      ],
      "type": "object"
    },
    "Statement": {
      "anyOf": [
        {
          "$ref": "#/definitions/ContentStatement"
        },
        {
          "$ref": "#/definitions/MustacheStatement"
        }
      ]
    },
    "StripFlags": {
      "additionalProperties": false,
      "properties": {
        "close": {
          "type": "boolean"
        },
        "open": {
          "type": "boolean"
        }
      },
      "required": [
        "open",
        "close"
      ],
      "type": "object"
    }
  }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/05-mustache-statement/unescaped-mustache.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "A simple mustache with unescaped output",
  "template": "{{{ value }}}",
  "input": { "value": "abc & < > \" ' ` = 123" },
  "output": "abc & < > \" ' ` = 123",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "MustacheStatement",
        "path": {
          "type": "PathExpression",
          "data": false,
          "depth": 0,
          "parts": ["value"],
          "original": "value",
          "loc": {
            "start": { "line": 1, "column": 4 },
            "end": { "line": 1, "column": 9 }
          }
        },
        "params": [],
        "escaped": false,
        "strip": { "open": false, "close": false },
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 13 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 13 }
    }
  }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/05-mustache-statement/white-space-control-escaped.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "White space should be removed when control characters are in place",
  "template": "|- {{~name}} | {{name~}} -|- {{~name~}} -|",
  "input": { "name": "joe" },
  "output": "|-joe | joe-|-joe-|",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "value": "|-",
        "original": "|- ",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 3 }
        }
      },
      {
        "type": "MustacheStatement",
        "escaped": true,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "name",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "loc": {
            "start": { "line": 1, "column": 6 },
            "end": { "line": 1, "column": 10 }
          }
        },
        "strip": { "open": true, "close": false },
        "loc": {
          "start": { "line": 1, "column": 3 },
          "end": { "line": 1, "column": 12 }
        }
      },
      {
        "type": "ContentStatement",
        "value": " | ",
        "original": " | ",
        "loc": {
          "start": { "line": 1, "column": 12 },
          "end": { "line": 1, "column": 15 }
        }
      },
      {
        "type": "MustacheStatement",
        "escaped": true,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "name",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "loc": {
            "start": { "line": 1, "column": 17 },
            "end": { "line": 1, "column": 21 }
          }
        },
        "strip": { "open": false, "close": true },
        "loc": {
          "start": { "line": 1, "column": 15 },
          "end": { "line": 1, "column": 24 }
        }
      },
      {
        "type": "ContentStatement",
        "value": "-|-",
        "original": " -|- ",
        "loc": {
          "start": { "line": 1, "column": 24 },
          "end": { "line": 1, "column": 29 }
        }
      },
      {
        "type": "MustacheStatement",
        "escaped": true,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "name",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "loc": {
            "start": { "line": 1, "column": 32 },
            "end": { "line": 1, "column": 36 }
          }
        },
        "strip": { "open": true, "close": true },
        "loc": {
          "start": { "line": 1, "column": 29 },
          "end": { "line": 1, "column": 39 }
        }
      },
      {
        "type": "ContentStatement",
        "value": "-|",
        "original": " -|",
        "loc": {
          "start": { "line": 1, "column": 39 },
          "end": { "line": 1, "column": 42 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 42 }
    }
  }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/06-path-expression/id-in-square-brackets.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "An id with special characters can be wrapped in square brackets",
  "template": "{{['].[ ].[0]}}",
  "input": { "'": { " ": ["success"] } },
  "output": "success",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "MustacheStatement",
        "escaped": true,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "['].[ ].[0]",
          "data": false,
          "depth": 0,
          "parts": ["'", " ", "0"],
          "loc": {
            "start": { "line": 1, "column": 2 },
            "end": { "line": 1, "column": 13 }
          }
        },
        "strip": { "open": false, "close": false },
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 15 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 15 }
    }
  },
  "originalAst": {
    "type": "Program",
    "body": [
      {
        "type": "MustacheStatement",
        "escaped": true,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "'. .0",
          "data": false,
          "depth": 0,
          "parts": ["'", " ", "0"],
          "loc": {
            "start": { "line": 1, "column": 2 },
            "end": { "line": 1, "column": 13 }
          }
        },
        "strip": { "open": false, "close": false },
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 15 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 15 }
    }
  }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/06-path-expression/path-expression-resolves-to-nothing.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "A path expressions that is resolved to nothing yields an empty string",
  "template": "{{person.name}}",
  "input": { "person": "Max" },
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "MustacheStatement",
        "escaped": true,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "person.name",
          "data": false,
          "depth": 0,
          "parts": ["person", "name"],
          "loc": {
            "start": { "line": 1, "column": 2 },
            "end": { "line": 1, "column": 13 }
          }
        },
        "strip": { "open": false, "close": false },
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 15 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 15 }
    }
  },
  "output": ""
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/01-introduction/example.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "A basic example with one mustache",
  "template": "Hello {{something}}",
  "input": { "something": "world" },
  "output": "Hello world",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "value": "Hello ",
        "original": "Hello ",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 6 }
        }
      },
      {
        "type": "MustacheStatement",
        "escaped": true,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "something",
          "data": false,
          "depth": 0,
          "parts": ["something"],
          "loc": {
            "start": { "line": 1, "column": 8 },
            "end": { "line": 1, "column": 17 }
          }
        },
        "strip": { "close": false, "open": false },
        "loc": {
          "start": { "line": 1, "column": 6 },
          "end": { "line": 1, "column": 19 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 19 }
    }
  }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/04-content-statement/escaped-content.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "Escaped mustache expression",
  "template": "\\{{abc}} \\{{{cde}}}",
  "input": {},
  "output": "{{abc}} {{{cde}}}",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "value": "{{abc}} {{{cde}}}",
        "original": "\\{{abc}} \\{{{cde}}}",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 19 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 1, "column": 19 }
    }
  },
  "originalAst": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "value": "{{abc}} {{{cde}}}",
        "original": "{{abc}} {{{cde}}}",
        "loc": {
          "start": { "line": 1, "column": 1 },
          "end": { "line": 1, "column": 19 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 1 },
      "end": { "line": 1, "column": 19 }
    }
  }
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/spec/05-mustache-statement/white-space-ignored-unescaped.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "White space around path expressions is",
  "template": "|- {{{~  \t\nname  \t\n}}} | {{{  \t\nname  \t\n~}}} -|- {{{~  \t\nname\t\n  ~}}} -|",
  "input": { "name": "joe" },
  "output": "|-joe | joe-|-joe-|",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "value": "|-",
        "original": "|- ",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 1, "column": 3 }
        }
      },
      {
        "type": "MustacheStatement",
        "escaped": false,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "name",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "loc": {
            "start": { "line": 2, "column": 0 },
            "end": { "line": 2, "column": 4 }
          }
        },
        "strip": { "open": true, "close": false },
        "loc": {
          "start": { "line": 1, "column": 3 },
          "end": { "line": 3, "column": 3 }
        }
      },
      {
        "type": "ContentStatement",
        "value": " | ",
        "original": " | ",
        "loc": {
          "start": { "line": 3, "column": 3 },
          "end": { "line": 3, "column": 6 }
        }
      },
      {
        "type": "MustacheStatement",
        "escaped": false,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "name",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "loc": {
            "start": { "line": 4, "column": 0 },
            "end": { "line": 4, "column": 4 }
          }
        },
        "strip": { "open": false, "close": true },
        "loc": {
          "start": { "line": 3, "column": 6 },
          "end": { "line": 5, "column": 4 }
        }
      },
      {
        "type": "ContentStatement",
        "value": "-|-",
        "original": " -|- ",
        "loc": {
          "start": { "line": 5, "column": 4 },
          "end": { "line": 5, "column": 9 }
        }
      },
      {
        "type": "MustacheStatement",
        "escaped": false,
        "params": [],
        "path": {
          "type": "PathExpression",
          "original": "name",
          "data": false,
          "depth": 0,
          "parts": ["name"],
          "loc": {
            "start": { "line": 6, "column": 0 },
            "end": { "line": 6, "column": 4 }
          }
        },
        "strip": { "open": true, "close": true },
        "loc": {
          "start": { "line": 5, "column": 9 },
          "end": { "line": 7, "column": 6 }
        }
      },
      {
        "type": "ContentStatement",
        "value": "-|",
        "original": " -|",
        "loc": {
          "start": { "line": 7, "column": 6 },
          "end": { "line": 7, "column": 9 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 7, "column": 9 }
    }
  },
  "originalParseError": true
}

=== nknapp/handlebars-ng/packages/@handlebars-ng/specification/src/pages/spec/03-template-syntax/content.hb-spec.json
{
  "$schema": "../schema/testcase.json",
  "description": "A simple template without mustaches",
  "template": "hello\nworld",
  "input": {},
  "output": "hello\nworld",
  "ast": {
    "type": "Program",
    "body": [
      {
        "type": "ContentStatement",
        "original": "hello\nworld",
        "value": "hello\nworld",
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 2, "column": 5 }
        }
      }
    ],
    "strip": {},
    "loc": {
      "start": { "line": 1, "column": 0 },
      "end": { "line": 2, "column": 5 }
    }
  }
}
